import {
  Binoculars,
  Calendar,
  CalendarDays,
  ChartLine,
  ChartPie,
  ClipboardList,
  Clapperboard,
  Clock,
  Columns3,
  Compass,
  FileText,
  Flag,
  Gauge,
  Gift,
  Globe,
  HeartHandshake,
  IdCard,
  Images,
  Layers,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Network,
  Newspaper,
  Palette,
  PenLine,
  Pencil,
  Phone,
  QrCode,
  Quote,
  Route,
  ScanSearch,
  Share2,
  SpellCheck,
  Star,
  Tags,
  Target,
  Type,
  UserRound,
  Users,
  Wallet,
  Waypoints,
  type LucideIcon,
} from "lucide-react";

// Ein Piktogramm je Werkzeug (Menü, Karten, Pfade). Eine Linienstärke, eine Familie (Lucide). Neue Werkzeuge tragen sich hier ein;
// der Test in lib/tool-icons.test.ts schlägt an, wenn ein Eintrag fehlt.
export const TOOL_ICONS: Record<string, LucideIcon> = {
  angebotsarchitektur: Layers,
  angebotsgrafik: Tags,
  "anlass-planer": ListChecks,
  anspruchsgruppen: Users,
  "bewertungs-kit": Star,
  bewertungsantwort: MessageSquare,
  botschaften: Megaphone,
  "budget-planer": Wallet,
  "caption-baukasten": Type,
  "content-ideen": Lightbulb,
  "content-kalender": CalendarDays,
  "content-saeulen": Columns3,
  "content-strategie": Route,
  "digitaler-auftritt-check": ScanSearch,
  empfehlungsprogramm: HeartHandshake,
  "engagement-rate": ChartLine,
  "gbp-feiertage": Clock,
  "icp-builder": Target,
  "ideen-aus-website": Globe,
  "kampagnen-planer": Flag,
  kanalstrategie: Share2,
  "kpi-baum": Network,
  kundenweg: Waypoints,
  "linkedin-profil": IdCard,
  markenplattform: Palette,
  medienmitteilung: Newspaper,
  "newsletter-check": Mail,
  nutzenversprechen: Gift,
  persona: UserRound,
  positionierung: Compass,
  "post-generator": PenLine,
  "posting-plan": Calendar,
  "qr-set": QrCode,
  "reifegrad-check": Gauge,
  "sponsoring-dossier": FileText,
  "story-post": Clapperboard,
  "strategie-einseiter": ClipboardList,
  swot: LayoutGrid,
  testimonial: Quote,
  "text-umschreiber": Pencil,
  textcheck: SpellCheck,
  "vereins-kommunikation": MessagesSquare,
  verzeichnisse: MapPin,
  "vorher-nachher": Images,
  wettbewerbsvergleich: Binoculars,
  "whatsapp-link": Phone,
  "zielgruppen-segmente": ChartPie,
};

type Props = { slug: string; className?: string };

/** Piktogramm des Werkzeugs, für Vorlesegeräte versteckt (der Name steht daneben). */
export function ToolIcon({ slug, className }: Props) {
  const Icon = TOOL_ICONS[slug] ?? Lightbulb;
  return <Icon aria-hidden="true" strokeWidth={1.6} className={className ?? "size-6"} />;
}
