import dynamic from "next/dynamic";
import type { ComponentType } from "react";

// Zuordnung slug → Tool-Client-Komponente. Getrennt von tools/index.ts (nur Konfigurationen),
// damit API-Routen und Sitemap keine Komponenten laden. `npm run new-tool <slug>` trägt hier ein
// (und ergänzt `import dynamic from "next/dynamic"`, falls es fehlt).
export const toolComponents: Record<string, ComponentType> = {
  "digitaler-auftritt-check": dynamic(() => import("./digitaler-auftritt-check/Tool")),
  "textcheck": dynamic(() => import("./textcheck/Tool")),
  "text-umschreiber": dynamic(() => import("./text-umschreiber/Tool")),
  "newsletter-check": dynamic(() => import("./newsletter-check/Tool")),
  "reifegrad-check": dynamic(() => import("./reifegrad-check/Tool")),
  "wettbewerbsvergleich": dynamic(() => import("./wettbewerbsvergleich/Tool")),
  "ideen-aus-website": dynamic(() => import("./ideen-aus-website/Tool")),
  "icp-builder": dynamic(() => import("./icp-builder/Tool")),
  "nutzenversprechen": dynamic(() => import("./nutzenversprechen/Tool")),
  "persona": dynamic(() => import("./persona/Tool")),
  "positionierung": dynamic(() => import("./positionierung/Tool")),
  "botschaften": dynamic(() => import("./botschaften/Tool")),
  "markenplattform": dynamic(() => import("./markenplattform/Tool")),
  "swot": dynamic(() => import("./swot/Tool")),
  "inhalte-saeulen": dynamic(() => import("./inhalte-saeulen/Tool")),
  "whatsapp-link": dynamic(() => import("./whatsapp-link/Tool")),
  "qr-set": dynamic(() => import("./qr-set/Tool")),
  "bewertungs-kit": dynamic(() => import("./bewertungs-kit/Tool")),
  "budget-planer": dynamic(() => import("./budget-planer/Tool")),
  "strategie-einseiter": dynamic(() => import("./strategie-einseiter/Tool")),
  "caption-baukasten": dynamic(() => import("./caption-baukasten/Tool")),
  "gbp-feiertage": dynamic(() => import("./gbp-feiertage/Tool")),
  "inhalte-ideen": dynamic(() => import("./inhalte-ideen/Tool")),
  "feiertagskalender": dynamic(() => import("./feiertagskalender/Tool")),
  "post-generator": dynamic(() => import("./post-generator/Tool")),
  "medienmitteilung": dynamic(() => import("./medienmitteilung/Tool")),
  "bewertungsantwort": dynamic(() => import("./bewertungsantwort/Tool")),
  "anspruchsgruppen": dynamic(() => import("./anspruchsgruppen/Tool")),
  "vereins-kommunikation": dynamic(() => import("./vereins-kommunikation/Tool")),
  "sponsoring-dossier": dynamic(() => import("./sponsoring-dossier/Tool")),
  "empfehlungsprogramm": dynamic(() => import("./empfehlungsprogramm/Tool")),
  "engagement-rate": dynamic(() => import("./engagement-rate/Tool")),
  "anlass-planer": dynamic(() => import("./anlass-planer/Tool")),
  "angebotsarchitektur": dynamic(() => import("./angebotsarchitektur/Tool")),
  "kpi-baum": dynamic(() => import("./kpi-baum/Tool")),
  "story-post": dynamic(() => import("./story-post/Tool")),
  "posting-plan": dynamic(() => import("./posting-plan/Tool")),
  "kundenweg": dynamic(() => import("./kundenweg/Tool")),
  "kampagnen-planer": dynamic(() => import("./kampagnen-planer/Tool")),
  "linkedin-profil": dynamic(() => import("./linkedin-profil/Tool")),
  "vorher-nachher": dynamic(() => import("./vorher-nachher/Tool")),
  "angebotsgrafik": dynamic(() => import("./angebotsgrafik/Tool")),
  "zielgruppen-segmente": dynamic(() => import("./zielgruppen-segmente/Tool")),
  "verzeichnisse": dynamic(() => import("./verzeichnisse/Tool")),
  "kanalstrategie": dynamic(() => import("./kanalstrategie/Tool")),
  "testimonial": dynamic(() => import("./testimonial/Tool")),
  "inhalte-strategie": dynamic(() => import("./inhalte-strategie/Tool")),
  // new-tool:components
};
